"""tables_2

Revision ID: 50db24b06248
Revises: 0528b8933251
Create Date: 2020-05-08 20:23:56.290876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50db24b06248'
down_revision = '0528b8933251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_timestamp', table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('system_id', sa.VARCHAR(length=140), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('cpu_usage', sa.FLOAT(), nullable=True),
    sa.Column('cpu_temp', sa.FLOAT(), nullable=True),
    sa.Column('disk_free', sa.FLOAT(), nullable=True),
    sa.Column('disk_used', sa.FLOAT(), nullable=True),
    sa.Column('disk_percent', sa.FLOAT(), nullable=True),
    sa.Column('cpu_cores_phys', sa.INTEGER(), nullable=True),
    sa.Column('cpu_freq_max', sa.FLOAT(), nullable=True),
    sa.Column('memory_total', sa.FLOAT(), nullable=True),
    sa.Column('memory_used', sa.FLOAT(), nullable=True),
    sa.Column('memory_percent', sa.FLOAT(), nullable=True),
    sa.Column('os', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index('ix_system_timestamp', 'system', ['timestamp'], unique=False)
    # ### end Alembic commands ###
