"""System table

Revision ID: 674e34bcf5ca
Revises: 2f13eff67087
Create Date: 2020-04-27 15:07:33.678640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674e34bcf5ca'
down_revision = '2f13eff67087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('cpu_usage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'cpu_usage')
    # ### end Alembic commands ###
