"""tables_orm

Revision ID: 6a4383a05be3
Revises: 50db24b06248
Create Date: 2020-05-10 12:36:41.254310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4383a05be3'
down_revision = '50db24b06248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_id', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('cpu_temp', sa.Float(), nullable=True),
    sa.Column('disk_free', sa.Float(), nullable=True),
    sa.Column('disk_used', sa.Float(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('cpu_cores_phys', sa.Integer(), nullable=True),
    sa.Column('cpu_freq_max', sa.Float(), nullable=True),
    sa.Column('memory_total', sa.Float(), nullable=True),
    sa.Column('memory_used', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('os', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_timestamp'), 'system', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_timestamp'), table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###
