"""new systemtable

Revision ID: 84f1e7de53ca
Revises: 1582640ba8e9
Create Date: 2020-05-01 16:39:24.337606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f1e7de53ca'
down_revision = '1582640ba8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('cpu_temp', sa.Float(), nullable=True))
    op.add_column('system', sa.Column('disk_free', sa.Float(), nullable=True))
    op.add_column('system', sa.Column('disk_percent', sa.Float(), nullable=True))
    op.add_column('system', sa.Column('disk_used', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'disk_used')
    op.drop_column('system', 'disk_percent')
    op.drop_column('system', 'disk_free')
    op.drop_column('system', 'cpu_temp')
    # ### end Alembic commands ###
