"""system table

Revision ID: a13a8763248e
Revises: a0e57cc26964
Create Date: 2020-01-06 05:45:19.146826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13a8763248e'
down_revision = 'a0e57cc26964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_timestamp'), 'system', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_timestamp'), table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###
